algorithms-are-fun-perhaps/algorithms-are-fun-perhaps

- JungMin/INF1_1.html
- JungMin/INF1_2.html
- JungMin/INF1_3.html
- JungMin/PRG_12925.html
- JungMin/PRG_12954.html
- JungMin/PRG_87389.html
공유한 PDF가 동일하므로 저 또한 생략하도록 하겠습니다.
자바스크립트를 사용한 기본문제
이 또한 공유한 PDF가 동일하므로 저 또한 생략하도록 하겠습니다.
1. if-else 조건문 
2. if-else 조건문
3. Math 메소드 
1. if-else 조건문을 사용해 최솟값을 비교했습니다. let answer으로 변수를 할당해 a,b,c 중 a,b를 먼저 비교해 더 작은 수를 넣고, 더 작은 수가 들어가 있는 answer와 c 중 더 작은 수를 비교하는 조건문을 사용해 최종적으로 가장 작은 수를 return 할 수 있도록 했습니다. 
2. 삼각형이 되는 조건이 '두 변의 합이 가장 긴 변보다 커야한다.'이기 때문에 가장 긴 변을 구할 변수와 a,b,c를 모두 합친 수가 들어갈 변수를 만들어두고 1번처럼 조건문을 활용해 가장 긴 변을 구한 뒤, '(세 변을 합한 수 - 가장 긴 변) > 가장 긴 변' 을 비교해 답을 반환했습니다.
3. 나누기와 Math 메소드를 사용해 쉽게 해결하였습니다. +1을 하는 방법도 있었으나 무조건 숫자를 올려주는 함수를 사용해 깔끔하게 마무리 하는 편이 좋다고 생각해 Math.ceil을 사용했습니다.
없습니다!
- [시간복잡도-지수/로그 시간](https://alissa1228.github.io/jekyll/update/2024/02/20/logBigONotation.html)
- 스택/큐 간단 정리...는 블로그 배포 오류로 [노션 링크](https://neat-homegrown-f51.notion.site/Stack-Queue-51ab42b57b424cabb95ff8944a2 …
> [2월 5주차 알고리즘 스터디] 문자열, 스택, 큐 / 윤정민

- JungMin/INF1_4.html
- JungMin/INF1_5.html
- JungMin/INF1_6.html
- JungMin/INF7_1.html
- JungMin/INF7_2.html
- JungMin/INF7_3.html
- JungMin/INF7_4.html
- JungMin/INF7_5.html
- JungMin/INF7_6.html
- JungMin/INF7_7.html
<br/>
**📍크레인 인형뽑기(스택)**
- 게임화면이 담긴 2차원 배열 board에서 주어진 moves 배열에 따라 인형을 뽑았을 때 터트려서 사라진 인형의 총 개수를 반환하는 문제입니다. 
|board|moves|result|
|------|---|---|
|[[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]]|[1,5,3,5,1,2,1,4]|4|
<br/>
**📍교육과정 설계(큐)**
- 수업설계가 필수 과목을 포함하고 해당 순서를 지켜 설계 되었는지를 체크하는 문제입니다. 
|입력|출력|
|---|---|
|CBA CBDAGE|YES|
<br/>
<br/>
**📍크레인 인형뽑기(스택)**
: 스택을 사용해 moves 배열에 따라 2차원 배열에 접근해 인형을 스택에 저장하고 같은 종류의 인형이 연속해서 스택에 쌓였을 경우, 사라지는 인형의 갯수를 구하는 문제입니다.
<br/>
**📍교육과정 설계(큐)**
: 큐를 사용해 수업설계에 필수 과목이 포함되어 있고 필수과목의 순서에 맞게 설계 되었는지를 체크해, 제대로 설계 되었다면 YES를 아니라면 NO를 반환해주는 문제입니다. 
<br/>
<br/>
**📍크레인 인형뽑기(스택)**
<br/>
입력:
- board 배열은 2차원 배열로 크기는 "5 x 5" 이상 "30 x 30" 이하입니다.
- board의 각 칸에는 0 이상 100 이하인 정수가 담겨있습니다
- 0은 빈 칸을 나타냅니다.
- 1 ~ 100의 각 숫자는 각기 다른 인형의 모양을 의미하며 같은 숫자는 같은 모양의 인형을 나타냅니다.
- …
> [2월 5주차 알고리즘 스터디] 스택, 큐 / 윤정민

- juhee/src/inf/bruteforce/Q01.java
- juhee/src/inf/bruteforce/Q02.java
- juhee/src/inf/bruteforce/Q03.java
- juhee/src/inf/bruteforce/Q04.java
- juhee/src/inf/bruteforce/Q05.java
입력된 자연수들 중에서 각 자연수의 자릿수의 합을 구하여, 그 합이 최대인 자연수를 출력하는 프로그램을 작성하되, 자릿수의 합이 같은 경우에는 원래 숫자가 더 큰 자연수를 선택하여 출력하는 문제입니다.
주어진 문자열에 대하여 각각의 자릿수에 해당하는 문자를 정수형으로 치환하여 연산하는 문제입니다.
입력:
- 첫 줄에 자연수의 개수 N(3<=N<=100)이 주어지고, 그 다음 줄에 N개의 자연수가 주어진다.
각 자연수의 크기는 10,000,000를 넘지 않는다.
출력:
- 자릿수의 합이 최대인 자연수를 출력한다.
엣지 케이스는 없었습니다!
- 사용한 자료구조: 배열
- 알고리즘: 크게 없었습니다.
너무나도 귀찮은 나머지 입력받은 문자열의 길이만큼 반목문을 돌렸습니다.
반복문마다 인덱스에 해당하는 문자를 문자열로 치환한 뒤 정수형으로 parse해줬습니다.
지금 생각해보니 그냥 subString써서 바로 정수형으로 바꿀걸 그랬습니다.
토의 사항은 없습니다!
선생님이 정해진 예산으로 학생들이 원하는 선물을 배송비와 상품가격을 합계를 예산 안에서 최대한 구매할 수 있는 수를 구하는 문제였습니다.
완전 탐색을 진행하되, 저의 경우 가장 가격이 적은 상품부터 구매를 했습니다. 그래야 최대 구매 개수를 도출 할 것이라 생각했습니다.
입력:
- 첫 번째 줄에 반 학생수 N(1<=N<=1000)과 예산 M(1<=M<=100,000,000)이 주어진다.
- 두 번째 줄부터 N줄에 걸쳐 각 학생들이 받고 싶은 상품의 가격과 배송비가 입력됩니다.
상품가격과 배송비는 각각 100,000을 넘지 않습니다. 상품가격은 짝수로만 …
> [3월 1 ~ 2주차 알고리즘 스터디] 브루트 포스 / 이주희

- JungMin/INF1_7.html
- JungMin/INF4_1.html
- JungMin/INF4_2.html
- JungMin/INF4_3.html
- JungMin/INF4_4.html
- JungMin/INF4_5.html
N개의 자연수가 주어지면 각각 숫자를 뒤집은 뒤 소수를 찾아, 소수들만 출력하는 문제입니다. 
입력:
- 자연수의 갯수 N과 N개의 자연수가 입력됩니다.
- 각 자연수의 크기는 100,000를 넘지 않습니다.
출력:
- 뒤집은 소수를 출력합니다.
- 출력 순서는 입력된 순서대로 출력합니다.
특별히 없습니다.
브루트 포스 알고리즘
1. 저는 string으로 숫자를 입력한다고 가정했기 때문에 split() 메서드를 사용해 배열로 만들어주었습니다.
2. for..of 문을 사용해 1번으로 만들어놨던 배열을 모두 돌며 숫자를 나누고(split()) 뒤집어서(reverse()) 다시 합칩니다(join())
3. 여기에서 정규표현식을 사용해 0을 삭제합니다(replace())
4. isPrime이라는 소수 판별 함수를 추가해 true하면 미리 만들어두었던 answer 배열에 뒤집어놓은 숫자를 Push합니다.
5. 소수는 자기만을 약수로 가지는 수로서, 각 숫자에 대해 2부터 해당 숫자의 제곱근까지 나눗셈을 해 소수를 판별하는 isPrime을 작성했습니다. 
이 문제에서는 없었습니당!
---
M번의 수학테스트 등수를 가지고 가능한 모든 조합을 탐색해, 그 중 짝을 만들 수 있는 멘토,멘티의 조합을 찾는 문제입니다. 멘토 학생이 모든 시험에서 멘티 학생보다 순위가 높을 경우 멘토-멘티 조합이 가능해집니다.
입력:
- 학생 수 N과 M이 주어집니다.
- M개의 줄에 걸쳐 수학 테스트 결과에 따라 학생번호가 제일 앞에서부터 1등,2등..N등으로 입력됩니다.
출력:
- 짝을 만들 수 있는 총 경우를 출력합니다.
특별히 …
> [3월 1 ~ 2주차 알고리즘 스터디] 브루트 포스 / 윤정민

- JungMin/INF6_1.html
- JungMin/INF6_2.html
- JungMin/INF6_3.html
- JungMin/INF6_4.html
- JungMin/INF6_5.html
- JungMin/INF6_6.html
- JungMin/INF6_7.html
일정한 크기의 캐시가 비어있는 상태에서 N개의 작업을 CPU가 차례로 처리한다면, 작업을 처리한 후의 캐시 메모리에서 가장 최근 사용된 작업부터 차례대로 출력해야하는 문제입니다. 문제에서는 
데이터 배열로 캐시 메모리를 만들고, array 관련 메소드를 사용해 LRU 알고리즘을 구현하는 문제였습니다. 
입력:
- 첫 번째 줄에 캐시의 크기인 S(3<=S<=10)와 작업의 개수 
- N(5<=N<=1,000)이 입력된다. 두 번째 줄에 N개의 작업번호가 처리순으로 주어진다. 작업번호는 1 ~100 이다.
출력:
- 마지막 작업 후 캐시메모리의 상태를 가장 최근 사용된 작업부터 차례로 출력합니다.
특별히 없습니다!
데이터 구조 : 배열
알고리즘 : LRU (Least Recently Used) 알고리즘
1. 답을 담을 cache 배열을 하나 만들고, 입력 받은 배열의 길이 만큼 반복문을 돌립니다.
2. 반복문 안에는 'cache에 이미 같은 수가 있다면 삭제해야' 했으므로  'array.indexOf()'메서드를 사용해  관련 인덱스를 알 수 있는 변수를 할당했습니다. 
3. 2번에서 할당한 변수를 사용해 만약 같은 수가 cache 배열에 있다면, 해당 수의 인덱스를 찾아 'array.splice()' 메서드를 사용해 삭제했습니다. 없으면 if 조건문에 걸리지 않으므로 자동으로 cache 배열에 들어가게 됩니다.
4.  여기에 추가로 캐시 메모리 만큼만 담아져야 하므로 캐시 메모리 길이가 넘어가면 맨 끝에 있는 건 삭제되도록 pop() 메서드를 사용했습니다.
5. 마지막으로 반복문을 모두 다 돌고 나온 캐시 …
> [3월 3주차 알고리즘 스터디] 정렬 / 윤정민

- juhee/src/inf/sorting/Q01.java
- juhee/src/inf/sorting/Q02.java
- juhee/src/inf/sorting/Q03.java
- juhee/src/inf/sorting/Q04.java
- juhee/src/inf/sorting/Q05.java
- juhee/src/inf/sorting/Q06.java
- juhee/src/inf/sorting/Q07.java
#13
N개의 평면상의 좌표(x, y)가 주어지면 모든 좌표를 오름차순으로 정렬하는 프로그램을 작성하
세요. 정렬기준은 먼저 x값의 의해서 정렬하고, x값이 같을 경우 y값에 의해 정렬합니다.
좌표를 클래스로 구현한 후 x와 y을 기준으로 정렬을 할 수 있는 코드를 작성하는 문제입니다.
입력:
- 첫째 줄에 좌표의 개수인 N(3<=N<=100,000)이 주어집니다.
- 두 번째 줄부터 N개의 좌표가 x, y 순으로 주어집니다. x, y값은 양수만 입력됩니다.
출력:
- N개의 좌표를 정렬하여 출력하세요.
- 엣지케이스는 없습니다~!
- 사용한 데이터 구조: 클래스, 배열
- 알고리즘: 정렬 알고리즘
- 클래스를 사용하여 좌표를 정의하였습니다. 자바에서 클래스는 사용자 정의 데이터로 사용되기도 하기 때문입니다. (자바의 정석 참고)
- 정수 x, y를 필드 값으로 갖는 클래스 Coordinate를 static 클래스로 생성하였습니다.
- 그 후 정렬에 사용되는 Comparable 클래스를 상속받습니다. 
- 부모 클래스인 Comparable에서 compareTo()매서드를 오버라이딩 해줍니다.
* source 객체와 target 객체의 x의 값이 같을 경우 y를 비교하고
* 아닐 경우 x의 값을 비교하도록 매서드를 오버라이딩 해줍니다.
- 그 후 배열에 각 x,y에 해당하는 좌표 클래스를 생성하여 저장한 후 Arrays.sort()를 활용하여 정렬합니다.
js에서는 한줄이면 되는 것에 신기할 따름입니다....
이번주까지는 제가 프로젝트 마감이어서 이론 정리까지 할 시간이 없었습니다....ㅠ 차주부터는 꼭 …
> [3월 3주차 알고리즘 스터디] 정렬 / 이주희

- JungMin/INF6_10.html
- JungMin/INF6_11.html
- JungMin/INF6_12.html
- JungMin/INF6_8.html
- JungMin/INF6_9.html
피로연장에 동시에 존재하는 최대 인원을 출력하는 문제입니다.
피로연에 참석하는 사람들 각각 오는 시간과 가는 시간을 나누어 배열에 저장한 후, 겹치는 이벤트(간격)를 효율적으로 계산해(그리디 알고리즘, 정렬) 동시에 존재하는 최대 인원을 구하는 문제입니다.
입력:
- 첫째 줄에 피로연에 참석할 인원수 N(5<=N<=100,000)이 주어집니다.
- 두 번째 줄부터 N줄에 걸쳐 각 인원의 오는 시간과 가는 시간이 주어집니다.
- 시간은 첫날 0시를 0으로 해서 마지막날 밤 12시를 72로 하는 타임라인으로 오는 시간과 가는 시간이 음이 아닌 정수로 표현됩니다.
출력:
- 첫째 줄에 피로연장에 동시에 존재하는 최대 인원을 출력하세요.
없습니다!
- 그리디 알고리즘
- 정렬
- 처음에는 미리 sort를 해놓고 배열 없이 가고자 했으나...이렇게 되면 시간대 별로 인원 수의 변화를 계산해야하므로 너무..너무 비효율적이라고 생각했습니다..
- 어쨌든 왔다면 count 증가 / 갔다면 count 감소이므로, 시간 별로 '참석 시간인지', '퇴장 시간인지'를 구분하기 위해 객체로 따로 담아준 후 정렬해주었습니다.
- 여기에 나간 걸 먼저 정리해줘야 count가 제대로 되기 때문에(들어온 걸 먼저 세버리면 제대로 count 되지 않음) localCompare() 메서드를 사용해 문자열을 사전 순으로 정렬해 설정해둔 'end' 가 먼저 정렬되도록 했습니다.
- forEach() 메서드를 사용해 배열을 돌며 type이 'start'면 증가, 'end'면 감소 되도록 했습니다.
- Math.max()를 사용해 각 이벤트가 …
> [3월 4주차 알고리즘 스터디] 그리디, 결정 알고리즘 / 윤정민

- juhee/src/inf/binarysearch/Q01.java
- juhee/src/inf/binarysearch/Q02.java
- juhee/src/inf/binarysearch/Q03.java
- juhee/src/inf/greedy/Q01.java
- juhee/src/inf/greedy/Q02.java
- juhee/src/inf/greedy/Q02_1.java
#16 
주어진 n개의 회의에 대해 각 회의의 시작 시간과 종료 시간이 주어졌을 때, 겹치지 않게 회의실을 사용할 수 있는 최대 회의 수를 찾는 문제입니다. 이 문제에서는 회의는 중간에 중단되지 않으며, 한 회의가 끝나면 바로 다음 회의가 시작될 수 있습니다.
주어진 회의들 중에서 겹치지 않게 회의실을 사용할 수 있는 최대 회의 수를 찾는 문제입니다.
입력:
- 첫째 줄에 회의의 수 n(1<=n<=100,000)이 주어진다. 둘째 줄부터 n+1 줄까지 각 회의의 정
보가 주어지는데 이것은 공백을 사이에 두고 회의의 시작시간과 끝나는 시간이 주어진다.
회의의 시작시간과 끝나는 시간의 조건은 (시작시간 <= 끝나는 시간)입니다.
출력:
- 첫째 줄에 최대 사용할 수 있는 회의 수를 출력
엣지 케이스 없습니다~! 
- 그리디 알고리즘
- 정렬 알고리즘
저는 Meeting이라는 클래스를 생성하여 필드 값으로 회의시작/종료 시간을 가지게 한 후,
Comparable 인터페이스를 상속받아서 회의 종료 시간이 빠른 순으로 정렬하도록 하였습니다.
그 후 loop를 돌여 회의 시작 시간이 회의 시간 이후일 경우 카운트하는 방식으로 집계한 후
최대값일 경우 해당 값을 저장하여 반환하도록 하였습니다.
크게 없습니다~!
주어진 N개의 마구간에 C마리의 말을 배치하여 가장 가까운 두 말의 거리가 최대가 되도록 하는 문제입니다.
마구간 간에는 중복된 좌표가 없으며, 각 마구간에는 한 마리의 말만 들어갈 수 있습니다.
이때 가장 가까운 두 말의 거리의 최댓값을 찾아 출력해야 합니다.
결정 알고리즘(이진탐색)을 활용하여 말들이 최대한 …
> [3월 4주차 알고리즘 스터디] 그리디, 결정 알고리즘 / 이주희

- JungMin/PRG_1.html
- JungMin/PRG_2.html
체육복을 도난 당한 학생 번호와 체육복을 가져온 학생들의 번호를 사용해 체욱수업을 들을 수 있는 학생의 최댓값을 구하는 문제입니다.
입력:
- 전체 학생의 수 n, 체육복을 도난당한 학생들의 번호가 담긴 배열 lost, 여벌의 체육복을 가져온 학생들의 번호가 담긴 배열 reserve가 매개변수로 주어집니다.
-전체 학생의 수는 2명 이상 30명 이하입니다.
- 체육복을 도난당한 학생의 수는 1명 이상 n명 이하이고 중복되는 번호는 없습니다.
- 여벌의 체육복을 가져온 학생의 수는 1명 이상 n명 이하이고 중복되는 번호는 없습니다.
- 
출력:
- 체육수업을 들을 수 있는 학생의 최댓값을 return하세요.
참고 할만한 케이스가 있어 공유합니다! student라는 객체를 생성해 체육복을 하나씩 할당한 뒤 접근하는 방식입니다.  
잃어버린 lost 배열 학생들은 -1을 해 체육복을 잃어버린 것으로 표현하고, reseve 배열 학생들은 +1을 해 여벌 체육복이 있다고 표기했습니다.
그 후 루프를 돌며 만약 학생이 여벌 옷을 가지고 있고 앞이나 뒤에 있는 학생이 옷이 없다면 체육복을 빌려주는 로직을 추가합니다.
```javascript
function solution(n, lost, reserve) {
const students = {};
let answer = 0;
for(let i = 1; i <= n; i++){
students[i] = 1;
}
lost.forEach(number => students[number] -= 1);
reserve.forEach(number => students[number] += …
```
> [4월 1주차 알고리즘 스터디] 정렬(심화), 트리 / 윤정민

- juhee/src/prg/queue/Q42626.java
- juhee/src/prg/queue/Q42862.java
- juhee/src/prg/queue/Q43238.java
- juhee/src/prg/queue/Q688646.java
#17 
인접한 두 풍선 중에서 번호가 더 작은 풍선을 터뜨리는 행위는 1번만 할 수 있는 조건에서 인접한 풍선을 터트리고 중앙 정렬하는 행위를 반복하여 마지막으로 남을 수 있는 풍선의 가지수를 구하는 문제입니다.
특정 인덱스를 기반으로 해당 인덱스의 값이 좌/우 요소들에 비하여 작은지 확인해야합니다. 마지막에 모든 풍선들을 터트리고 2개가 남았을 때 해당 인덱스가 좌/우변 풍선보다 작아야하기 때문이지요.
입력:
- 일렬로 나열된 풍선들의 번호가 담긴 배열 a가 주어집니다.
출력:
- 풍선들을 1개만 남을 때까지 터트렸을 때 최후까지 남기는 것이 가능한 풍선들의 개수를 return 하도록 solution 함수를 완성해주세요.
엣지케이스는 특별히 없었습니다.
트리라고는 하지만 사실 정확하게 어떻게 트리를 구현한 건지 저는 잘모르겠습니다.
저는 배열과 탐색 알고리즘을 사용하였습니다.
풍선 배열에 대하여 두번째 인덱스 ~ 마지막 인덱스, 마지막 전 인덱스 ~ 첫번째 인덱스를 범위로하여 loop를 돕니다.
매 loop마다 해당 인덱스가 최소값일 경우 해당 인덱스의 값으로 바꿔주고 배열에 값을 할당합니다.
배열의 길이가 1일 경우 답을 1로 반환하고,
배열의 길이가 2보다 크거나 같을 경우 정답을 2로 할당한 후
배열을 돌면서 해당 인덱스의 값이 각각 좌/우변의 최소값보다 작은지 확인한 후 작을 경우 정답을 증가시킵니다.
벽느꼈습니다.... 중간고사 기간이라 시간이 부족하기도 했고, 문제 접근 방법자체를 생각하지 못하여 포기한 문제입니다...!
입국 심사를 기다리는 사람 수 'n'과 각 심사관이 한 명을 심사하는데 …
> [4월 1주차 알고리즘 스터디] 정렬(심화), 트리 / 이주희

- juhee/src/inf/graph/Q04.java
- juhee/src/inf/graph/Q05.java
- juhee/src/inf/graph/Q06.java
- juhee/src/inf/graph/Q07.java
#26 
주어진 집합을 조합하여 2개의 부분집합으로 나눈다.
이때 두 부분집합은 서로소(disjoint) 집합이다.
두 집합의 같은 경우가 있을 경우 "YES"를 없을 경우 "NO"를 출력하는 프로그램을 작성하라.
깊이 우선 탐색을 활용하여 모든 부분 집합의 경우를 확인하고, 조건에 맞는지 확인하는 프로그램을 작성.
입력:
- 첫 번째 줄에 자연수 N(1<=N<=10)이 주어집니다.
- 두 번째 줄에 집합의 원소 N개가 주어진다. 각 원소는 중복되지 않으며, 그 크기는 1,000,000 이하입니다.
출력:
- 첫 번째 줄에 “YES" 또는 ”NO"를 출력한다.
- 크게 없습니다.
- 배열 & 그래프 이론 (깊이 우선 탐색)
- 원소를 저장하는 배열 arr과 해당 인덱스의 사용여부를 나타내는 배열 ch
- 깊이 0부터 하여 해당 인덱스의 사용여부를 할당한 후 다음 깊이를 재귀함수의 인덱스로 할당
- 깊이가 N일 때 N만큼 loop가 돌며 ch의 값이 1일 경우 변수 sum에 해당 원소를 더해준다.
- 전체 배열의 합계  - 해당 부분집합의 합 = 해당 부분 집합의 합일 경우 "YES"를 리턴
- DFS 매서드는 일단 외우는 것도 좋은 것 같아요...!
철수는 그의 바둑이들을 데리고 시장에 가려고 한다. 그런데 그의 트럭은 C킬로그램 넘게 태
울수가 없다. 철수는 C를 넘지 않으면서 그의 바둑이들을 가장 무겁게 태우고 싶다.
N마리의 바둑이와 각 바둑이의 무게 W가 주어지면, 철수가 트럭에 태울 수 있는 가장 무거운
무게를 구하는 프로그램을 작성하세요.
깊이 우선 탐색을 활용하여 모든 바둑이들의 조합에 대하여 …
> [5월 2주차 알고리즘 스터디] 그래프이론 - 깊이 우선 탐색 이주희

- JungMin/INF8_4.html
- JungMin/INF8_5.html
- JungMin/INF8_6.html
- JungMin/INF8_7.html
#26
자연수 N이 주어지면 1부터 N까지의 원소를 갖는 집합의 부분집합을 모두 출력하는 프로그램을 작성하세요.
DFS 방식으로 공집합을 제외한 부분집합을 모두 출력하는 문제입니다.
입력:
- 첫 번째 줄에 자연수 N(1<=N<=10)이 주어집니다.
출력:
- 첫 번째 줄부터 각 줄에 하나씩 부분집합을 아래와 출력예제와 같은 순서로 출력한다.
- 단 공집합은 출력하지 않습니다.
특별히 없습니다!
- 배열 & DFS
- Array.from 메서드를 사용해 각 원소가 부분집합에 포함되는지 체크할 때 쓸 배열 생성 및 초기화 합니다.
- 재귀 함수를 사용해 현재의 깊이 또는 노드를 나타내는 v를 매개변수로 받아, 두 갈래로 나누어 v라는 원소를 포함하는 경우 ch[v]이 1이 되도록 하거나 포함하지 않으면 ch[v]가 0이 되도록 합니다. 
- v가 n+1와 같아지면 부분 집합을 완성한 것으로 간주하고, for문을 사용해 체크용 배열 ch 중 1로 들어온 것들(=부분집합)을 출력합니다. 
- 미리 만들어두었던 answer 배열에 결과들을 넣되, 공집합을 빼고 넣기 위해 tmp 길이가 0 이상 일 때만 answer로 push 되도록 합니다. 
없었습니다!
----
이번 정보올림피아드대회에서 좋은 성적을 내기 위하여 현수는 선생님이 주신 N개의 문제를 풀려고 합니다. 각 문제는 그것을 풀었을 때 얻는 점수와 푸는데 걸리는 시간이 주어지게 됩 니다. 제한시간 M안에 N개의 문제 중 최대점수를 얻을 수 있도록 해야 합니다. (해당문제는 해당시간이 걸리면 푸는 걸로 간주한다, 한 유형당 한개만 풀 수 있습니다.)
주어진 …
> [5월 2주차 알고리즘 스터디] 그래프이론 - 깊이 우선 탐색 / 윤정민

- JungMin/INF8_10.html
- JungMin/INF8_11.html
- JungMin/INF8_12.html
- JungMin/INF8_13.html
- JungMin/INF8_14.html
- JungMin/INF8_15.html
- JungMin/INF8_8.html
- JungMin/INF8_9.html
#30 
1부터 N까지 번호가 적힌 구슬이 있습니다. 이 중 중복을 허락하여 M번을 뽑아 일렬로 나열 하는 방법을 모두 출력하는 문제입니다
재귀함수를 사용해 M번 만큼 뽑아 나올 수 있는 경우의 수를 출력하는 문제입니다.
입력:
- 첫 번째 줄에 자연수 N(3<=N<=10)과 M(2<=M<=N) 이 주어집니다.
출력:
- 첫 번째 줄에 결과를 출력합니다. 맨 마지막 총 경우의 수를 출력합니다. 출력순서는 사전순으로 오름차순으로 출력합니다.
- DFS(깊이우선탐색), 배열
- 구슬 번호 범위와 뽑는 횟수를 solution 함수의 인자로 주고, 재귀 함수에 빈 배열을 넣어 함수를 호출합니다.
- 호출된 함수는 DFS가 받은 배열의 길이가 뽑는 횟수와 같아지면 join 메서드를 사용해 answer 배열에 추가하고 종료합니다.
- 만약 배열의 길이가 뽑는 횟수와 같지 않다면 for문이 돌면서 현재 배열 arr에 숫자 i를 추가한 새로운 배열(concat 메서드를 사용)로 DFS를 재호출. 이런 방식으로 모든 가능한 경우싀 수를 탐색합니다.
- 모든 탐색이 끝난 후에는 forEach 메서드를 사용해 answer에 있는 모든 결과를 console.log()로 출력합니다.
없었습니다!
-------
다음 공식을 사용하여 재귀를 이용해 조합수를 구해주는 프로그램을 작성하세요.
재귀함수를 이용하되 메모이제이션을 위한 2차원 배열을 생성해 중복계산을 피해 조합수를 구하는 문제였습니다.
- 첫째 줄에 자연수 n(3<=n<=33)과 r(0<=r<=n)이 입력됩니다.
- 첫째 줄에 조합수를 출력합니다.
- DFS(깊이우선탐색)
- …
> [5월 3주차 알고리즘 스터디] 그래프 이론 - 넓이 우선 탐색 / 윤정민

- JungMin/INF8_10.html
- JungMin/INF8_11.html
- JungMin/INF8_12.html
- JungMin/INF8_13.html
- JungMin/INF8_14.html
- JungMin/INF8_15.html
- JungMin/INF8_8.html
- JungMin/INF8_9.html
- juhee/src/inf/graph/Q08.java
- juhee/src/inf/graph/Q09.java
- juhee/src/inf/graph/Q10.java
- juhee/src/inf/graph/Q11.java
- juhee/src/inf/graph/Q12.java
- juhee/src/inf/graph/Q13.java
- juhee/src/inf/graph/Q14.java
- juhee/src/inf/graph/Q15.java
- juhee/src/prg/queue/Q42586.java
- juhee/src/prg/stack/Q12909.java
#30 
1부터 N까지 번호가 적힌 구슬이 있습니다. 이 중 M개를 뽑는 방법의 수를 출력하는 프로그램을 작성하세요.
DFS를 활용해서 비복원 추출하는 방법의 수를 출력합니다.
입력:
- 첫 번째 줄에 자연수 N(3<=N<=10)과 M(2<=M<=N) 이 주어집니다.
출력:
- 첫 번째 줄에 결과를 출력합니다. 맨 마지막 총 경우의 수를 출력합니다.
출력순서는 사전순으로 오름차순으로 출력합니다.
특별이 없습니다!
DFS 사용했습니다.
- 재귀 함수의 인자를 L과 D로 설정합니다.
- 1부터 N까지 반복문을 돌며 깊이를 1씩 증가하며 재귀함수를 호출합니다. 이때 D의 값은 i +1로 설정해서 비복원 추출을 구현합니다.
크게 없습니다!
N개의 정수가 주어지면 그 숫자들 중 K개를 뽑는 조합의 합이 임의의 정수 M의 배수인 개수
는 몇 개가 있는지 출력하는 프로그램을 작성하세요.
DFS를 활용하여 모든 수들의 조합을 조회한 후 해당 조합의 합이 임의의 정수 M의 배수인지 확인하는 문
입력:
- 첫줄에 정수의 개수 N(3<=N<=20)과 임의의 정수 K(2<=K<=N)가 주어지고,
- 두 번째 줄에는 N개의 정수가 주어진다.
- 세 번째 줄에 M이 주어집니다.
출력:
-총 가지수를 출력합니다.
특별히 없습니다!
- 깊이 우선 탐색
- 이전 문제와 같이 비복원 추출된 수의 집합을 표현합니다.
- 이때 메모이제이션을 활용하여 일차원 배열을 만들어 조합의 합이 배열에 있을 경우 검증하는 로직을 생략하도록합니다.
늦어서 죄송합니다...!
> [5월 3주차 알고리즘 스터디] 그래프 이론 - 넓이 우선 탐색 / 이주희

- juhee/src/ltc/ValidParentheses.java
- juhee/src/ltc/graph/AllPathFromSourceToTarget.java
- juhee/src/ltc/heap/MinimumNumberGame.java
- juhee/src/ltc/heap/SmallestInfiniteSet.java
- juhee/src/ltc/stack/ValidParentheses.java
- juhee/src/prg/queue/Q42586.java
- juhee/src/prg/stack/Q12909.java
- juhee/src/prg/stack/Q42584.java
#33 
주어진 붕대의 정보와 공격의 정보에 맞게 캐릭터의 체력을 구하는 문제였습니다.
https://school.programmers.co.kr/learn/courses/30/lessons/250137
구현문제였습니다. 요구사항에 맞게 회복/피격에 대한 기능을 구현하면 됩니다.
입력:
- 붕대 감기 기술의 시전 시간, 1초당 회복량, 추가 회복량을 담은 1차원 정수 배열 bandage와 최대 체력을 의미하는 정수 health, 몬스터의 공격 시간과 피해량을 담은 2차원 정수 배열 attacks가 매개변수로 주어집니다.
출력:
- 모든 공격이 끝난 직후 남은 체력을 return 하도록 solution 함수를 완성해 주세요. 만약 몬스터의 공격을 받고 캐릭터의 체력이 0 이하가 되어 죽는다면 -1을 return 해주세요.
특별이 없습니다!
- Heap 사용했습니다.
- 공격에 대하여 클래스를 구현하여 PriorityQueue에 넣고 사용했습니다.
- 0초 ~ 마지막 공격 시간까지 LOOP
- 공격이 있을 경우 체력 감소, 체력이 0보다 작을 경우 -1 반환
- 공격이 없을 경우 bandage 성능에 따라 체력 증가
- 연속 성공 카운트 증가, 최대 연속 횟수 도달 시 추가 체력 증가
- 최대 체력 도달 시에는 체력 증가
- 위의 기능들을 직접 구현했습니다. 특별한 풀이 방법은 없네요^^;
크게 없습니다!
- 달리기 현재 순서가 주어지고, 호명되는 선수는 앞의 선수를 추월합니다.
- 호명이 끝난 시점의 달리기 순위를 구합니다.
해시를 활용하여 푸는 문제였답니다.
- 입력: 선수들의 이름이 1등부터 현재 등수 …
> [5월 4주차 알고리즘 스터디] 자유 문제풀이/ 이주희

- JungMin/PRG_176963.html
- JungMin/PRG_178871.html
- JungMin/PRG_250137.html
- JungMin/PRG_258712.html
#33 
친구들이 이번 달까지 선물을 주고 받은 기록을 바탕으로 다음 달에 누가 선물을 많이 받을지 예측하려고 합니다. 규칙은 아래와 같습니다.
- 두 사람이 선물을 주고받은 기록이 있다면, 이번 달까지 두 사람 사이에 더 많은 선물을 준 사람이 다음 달에 선물을 하나 받습니다.
- 두 사람이 선물을 주고받은 기록이 하나도 없거나 주고받은 수가 같다면, 선물 지수가 더 큰 사람이 선물 지수가 더 작은 사람에게 선물을 하나 받습니다.
- 선물 지수는 이번 달까지 자신이 친구들에게 준 선물의 수에서 받은 선물의 수를 뺀 값입니다.  
- 만약 두 사람의 선물 지수도 같다면 다음 달에 선물을 주고받지 않습니다.
위의 규칙대로 다음 달에 선물을 주고 받을 때 선물을 가장 많이 받을 친구가 받을 선물의 수를 반환해야하는 문제입니다. 
각 친구들이 선물을 주고 받은 기록을 바탕으로, 규칙에 맞게 각 친구의 선물지수를 계산하고 다음 달에 받을 선물의 수를 예측해 가장 많이 받을 친구의 선물 수를 반환해야합니다.  
입력:
- 친구들의 이름을 담은 1차원 문자열 배열 friends 이번 달까지 친구들이 주고받은 선물 기록을 담은 1차원 문자열 배열 gifts가 매개변수로 주어집니다. 
출력:
- 다음달에 가장 많은 선물을 받는 친구가 받을 선물의 수를 반환해야 합니다.
- 해시맵과 이차원 배열, for 반복문을 사용했습니다.
- 친구들 수를 나타내는 length, 각 친구들의 선물 지수를 저장하기 위한 배열 giftPoints, 친구들 이름을 배열 인덱스로 매핑할 객체 index, 친구들 간의 선물 교환 기록을 저장할 …
> [5월 4주차 알고리즘 스터디] 자유 문제풀이 / 윤정민

- JungMin/INF5_1.html
- JungMin/INF5_2.html
- JungMin/INF5_3.html
- JungMin/INF5_4.html
- JungMin/INF5_5.html
- JungMin/INF5_6.html
- JungMin/INF5_7.html
- JungMin/INF5_8.html
#35 
학생 수 N만큼의 투표용지에 쓰여져 있는 문자열을 가지고 해쉬를 사용해 학습회장으로 선택된 기호를 찾아내는 문제입니다
map 관련 메소드를 사용해 해쉬맵을 만들고 forEach를 사용해 해당 값에 접근해 구하는 문제였습니다.
입력:
- 첫 줄에는 반 학생수 N(5<=N<=50)이 주어집니다.
- 두 번째 줄에 N개의 투표용지에 쓰여져 있던 각 후보의 기호가 선생님이 발표한 순서대로 문자열로 입력됩니다.
출력:
- 학급 회장으로 선택된 기호를 출력합니다.
- 특별히 없습니다!
-해쉬맵 사용했습니다.
- 답으로 반환할 answer와 제일 많이 투표를 받은 값을 찾기 위해 max 를 초기화해줍니다.
- new Map()을 사용해 해쉬맵을 만들고 for..of 루프를 사용해 해쉬맵에 키와 값을 담습니다. 이 때 has(), set(), get() 등의 메소드를 사용합니다. 
- 해쉬맵에 키와 값이 세팅됐으면 forEach를 사용해 값 중 가장 큰 값을 찾아냅니다. max보다 값이 크다면 max에 값을 넣고 answer에 해당 값의 키를 넣습니다. 
- 없습니다! 얘는 정말 정석으로 풀면 되는 문제인 거 같았어요
---
길이가 같은 두 개의 단어가 주어지면 두 단어가 아나그램인지 판별하는 문제입니다.
- 해쉬맵과 forEach를 사용해  두 개 객체의 key와 value를 비교해 답을 구하는 문제였습니다.
입력:
- 첫 줄에 첫 번째 단어가 입력되고, 두 번째 줄에 두 번째 단어가 입력됩니다. 
- 단어의 길이는 100을 넘지 않습니다.
출력:
- 두 단어가 아나그램이면 “YES"를 출력하고, 아니면 …
> [6월 2주차 알고리즘 스터디] 효율성(투포인터 알고리즘, 슬라이딩윈도우, 해쉬) 윤정민

- JungMin/INF9_1.html
- JungMin/INF9_2.html
- JungMin/INF9_3.html
- JungMin/INF9_4.html
- JungMin/INF9_5.html
- JungMin/INF9_6.html
- JungMin/INF9_7.html
- JungMin/LTC_valid-parentheses.html
- JungMin/PRG_1845.html
- JungMin/PRG_563109.html
#39 
7*7 격자판 미로가 주어집니다. 출발점은 (1,1), 도착점은 (7,7) 좌표이며 격자판의 1은 벽이고 0은 통로입니다. 주어진 미로를 탐색하고, 미로를 탈출할 수 있는 경로의 수를 출력하는 문제입니다.
- DFS를 사용해 2차원 배열을 상하좌우 방향으로 돌며 경로를 체크해 미로탈출 총 가짓수를 출력하면 됩니다.
입력:
- 7*7 격자판의 정보가 주어집니다.
출력:
-첫 번째 줄에 경로의 가지수를 출력합니다.
딱히 없었습니다!
- DFS:깊이우선탐색 알고리즘 사용했습니다.
- 가짓수를 세기 위한 answer를 선언해준 뒤, 상하좌우로 움직일 dx,dy를 초기화해줍니다.
- D(0,0) -> 위 D(-1,0)/ 오른쪽 D(0,1)/ 아래 D(1,0)/ 왼쪽 D(0,-1)
- 2차원 배열을 돌 DFS 함수를 만들어줍니다. 우리는 0,0에서 출발했기 때문에 (6,6)에 도착하면 answer을 증가시킵니다.
- 도착지점에 도착하기 전까지는 for loop를 사용해 각 방향의 이동을 위해 4번 반복하도록 해주고 현재 위치에서 각 방향으로 이동한 다음 좌표를 계산한 nx, ny에 넣어줍니다. 
- 만약 다음 좌표가 nx, ny 0이상이고 방문한 좌표가 0이면(=통로면) 해당 부분을 체크하고 DFS 함수를 호출합니다. 호출 후 탐색이 끝나면 좌표를 0으로 설정해 체크를 해제합니다. (다른 경로에서 위치를 다시 탐색할 수 있도록)
- 모든 탐색이 끝난 후 answer를 리턴해 가짓수를 반환합니다. 
- 특별히 없었습니다!
--
- N*N 섬나라 아일랜드 지도가 격자판 정보로 주어집니다. 0은 바다이며 1은 …
> [6월 3주차 알고리즘 스터디] BFS/DFS 활용 윤정민

- juhee/src/inf/graphadvance/Q02.java
- juhee/src/inf/graphadvance/Q03.java
- juhee/src/inf/graphadvance/Q04.java
- juhee/src/inf/graphadvance/Q05.java
#39 
현수가 스카이콩콩을 타고 송아지를 찾아 떠나는 여정이 담긴 문제입니다.
우리의 똑똑한 현수는 걷기보다는 효율적으로 스카이 콩콩을 타기로 하였습니다.
스카이 콩콩은 한번의 점프로 {-1, 1, 5}씩 갈 수 있습니다.
S에서 시작해서 E에 도착하는데 몇번의 점프가 필요할까요.
BFS를 활용하여 -1, 1, 5 씩 이동하는 좌표들에 대하여 E인지 확인하는 문제입니다.
입력:
- 첫 번째 줄에 현수의 위치 S와 송아지의 위치 E가 주어진다. 직선의 좌표 점은 1부터 10,000까지이다.
출력:
- 점프의 최소횟수를 구한다. 답은 1이상입니다.
- 엣지 케이스는 크게 없었습니다.
- BFS를 활용하였습니다.
- 좌표를 담기 위하여 일차원 배열 ch[]를, 한번에 움직일 수 있는 거리를 int[] steps로 사용하였습니다.
- LinkedList<Integer>를 활용하여 n번 점프하였을 때 갈 수 있는 좌표들을 담습니다.
- 해당 좌표의 범위 및 방문여부에 대한 검증을 진행한 후 이상이 없을 경우 해당 좌표에 해당하는 값을 큐에 넣어줍니다.
- 매 loop마다 카운트를 1씩 증가시킨 후, E에 도착하였을 때 카운트를 반환합니다.
- 아실 것 같지만 공유해봅니다!
- 저는 요즘 코드를 작성할 때 code smell을 경계해보기로 했습니다.
- 특히 분기문에서 if ~ else if를 열거하기 보다는, early return을 활용하여 코드를 작성해보기로 했습니다.
- Early return 패턴은 일반적으로 특정 조건이 만족되지 않으면 함수의 실행을 일찍 종료시키는 방식을 의미합니다.
- 예시
``` …
```
> [6월 3주차 알고리즘 스터디] BFS/DFS 활용 이주희

- juhee/src/inf/dynamic/Q01.java
- juhee/src/inf/dynamic/Q02.java
- juhee/src/inf/dynamic/Q03.java
- juhee/src/inf/dynamic/Q04.java
- juhee/src/inf/dynamic/Q05.java
- juhee/src/inf/dynamic/Q06.java
#43
N개의 자연수로 이루어진 수열이 주어졌을 때, 그 중에서 가장 길게 증가하는(작은 수에서 큰 수로) 원소들의 집합을 찾는 프로그램을 작성하는 문제입니다.
DP를 활용하여 LIS를 구하면 되는 문제입니다.
입력
- 첫째 줄은 입력되는 데이터의 수 N(3≤N≤1,000, 자연수)를 의미하고,
- 둘째 줄은 N개의 입력데이터들이 주어진다.
출력
- 첫 번째 줄에 부분증가수열의 최대 길이를 출력한다.
- 엣지 케이스는 크게 없었습니다.
- DP를 활용하여 문제를 해결합니다.
1. dy[i]는 arr[i]의 값을 마지막 항으로 하는 배열의 최대 길이로 초기화합니다.
2. dy[0] = 1로 초기화
3. 1부터 n까지 loop를 돌며 arr[n]의 값이 앞의 인덱스들의 값보다 크면 dy[i] + 1의 값을 할당 합니다.
4. 배열의 가장 큰 수를 반환합니다.
없습니다!
- 주어진 동전조합을 활용하여 잔돈을 가장 적게 주는 조합을 구합니다.
냅색 알고리즘을 활용하여 동전을 가장 적게 쓰는 조합을 구합니다.
입력
- 첫 번째 줄에는 동전의 종류개수 N(1<=N<=50)이 주어진다.
- 두 번째 줄에는 N개의 동전의 종류가 주어지고, 그 다음줄에 거슬러 줄 금액 M(1<=M<=500)이 주어진다.
출력
- 첫 번째 줄에 거슬러 줄 동전의 최소개수를 출력한다.
- 엣지 케이스는 크게 없어보입니다.
- DP(냅색 알고리즘)
- 저는 반복문을 돌며 해당 금액 - 동전의 값을 하는 이유가 해당 동전을 꼭 사용하는 대신 금액이 감소하는 것으로 이해하였습니다!
- 그랬을 때 해당 동전을 사용하지 않은 경우와 비교하여 최소값을 …
> [6월 4주차 알고리즘 스터디] DP / 이주희

- JungMin/INF10_1.html
- JungMin/INF10_2.html
- JungMin/INF10_3.html
- JungMin/INF10_4.html
- JungMin/INF10_5.html
- JungMin/INF9_7.html
#42 
N개의 돌로 만들어놓은 돌다리를 한 번에 한 칸 또는 두 칸씩 갈 수 있을 때, 철수가 개울을 건너는 방법은 몇 가지인지 구하는 문제입니다.  
- DP 알고리즘과 피보나치 수열 방식을 활용해 푸는 문제였습니다.
입력:
-첫째 줄은 돌의 개수인 자연수 N(3≤N≤45)이 주어집니다.
출력:
- 첫 번째 줄에 개울을 건너는 방법의 수를 출력합니다.
특별히 없었습니다!
- 배열
- DP 알고리즘
- 피보나치 수열 방식
- 돌다리 수만큼 dp용 배열을 만들어줍니다. 해당 배열을 메모이제이션을 위한 배열이며 다리를 건너는 방법의 수를 저장합니다. 
- 배열의 길이는 개울을 건너는 것까지 구해야하므로 도착지점까지 추가해 n+2를 해줍니다.
- 먼저 dp[1], dp[2]를 초기화해 줍니다. 
- ex)
- dp[1] =1 -> 첫 번 째 돌다리까지 가는 방법의 수 //1  
- dp[2]=2 -> 두 번째 돌다리까지 가는 방법의 수  //1+1 , 2
- 초기화한 dp[1], dp[2]를 사용해 for loop로 피보나치 수열과 유사하게 계산해줍니다. 
- 답을 반환할 때는 도착 후 돌다리를 건너고 나서기 때문에 n+1 위치로 출력해줍니다.
특별히 없습니다!
--
현수는 N개의 문제를 풀어야 합니다. 각 문제는 점수와 푸는 시간이 주어지며, 제한시간 M 안에 최대 점수를 얻도록 문제를 선택해야 합니다. (각 문제는 한 번만 풀 수 있습니다.)
- DP 알고리즘을 사용해 시간당 풀 수 있는 문제의 최대 점수를 저장할 배열을 만들고 이중 for문을 사용해 최대 점수를 구하는 문제입니다.
입력:
-첫 번째 줄에 …
> [6월 4주차 알고리즘 스터디] DP / 윤정민

- juhee/src/inf/pccp/Q01.java
- juhee/src/inf/pccp/Q02.java
#45
세로길이가 n 가로길이가 m인 격자 모양의 땅 속에서 석유가 발견되었습니다. 석유는 여러 덩어리로 나누어 묻혀있습니다. 당신이 시추관을 수직으로 단 하나만 뚫을 수 있을 때, 가장 많은 석유를 뽑을 수 있는 시추관의 위치를 찾으려고 합니다. 
BFS를 활용해서 각 유전에서 뽑아낼 수 있는 기름량을 자료구조에 저장한 후 각 파이프가 지나가는 유전을 구합니다.
입력
- 석유가 묻힌 땅과 석유 덩어리를 나타내는 2차원 정수 배열 land가 매개변수로 주어집니다.
출력
-  이때 시추관 하나를 설치해 뽑을 수 있는 가장 많은 석유량을 return
- 엣지 케이스는 크게 없었습니다.
- BFS를 활용하여 유전의 크기를 구합니다.
1. 저의 경우 광구와 광구의 유전량을 구했습니다.
2. 2광구부터 시작해 land에 대하여 loop를 돌며 같은 유전일 경우 같은 번호를 부여했습니다.
3. 그리고 Map<Integer. Integer>에 각 광구에 있는 석유량을 입력했습니다.
4. 그 후 파이프 별로 Set<Integer>를 활용하여 몇광구를 지나는지 확인햇습니다. (중복을 허용하지 않기 위하여 Set을 사용했어요.)
5. 각 파이프별로 Map을 활용하여 지나간 광구들에 해당하는 유전량을 더하여 답을 구했어요~!
없습니다!
요즘은 이론 정리를 못해요....ㅠ
> [7월 2주차 알고리즘 스터디] PCCP 기출문제 / 이주희

- juhee/src/prg/bruteforce/Q161989.java
- juhee/src/prg/bruteforce/Q161990.java
- juhee/src/prg/bruteforce/Q172928.java
- juhee/src/prg/hash/Q160586.java
- juhee/src/prg/hash/Q42576.java
- juhee/src/prg/stack/Q42586.java
- juhee/src/prg/stack/Q76502.java
- juhee/src/prg/tree/Q12985.java
#47 #50
- 로봇 강아지가 주어진 방향과 거리만큼 이동합니다.
- 경로에 장애물이 있거나, 범위를 벗어나면 해당 명령은 이행하지 않고 다음 명령을 진행합니다.
- 주어진 명령들의 결과값인 로봇 강아지의 좌표를 구하세요.
단순한 배열을 활용한 문제풀이였습니다.
입력:
- 원을 나타내는 문자열 배열 park, 
- 로봇 강아지가 수행할 명령이 담긴 문자열 배열 routes
출력:
- 로봇 강아지가 모든 명령을 수행 후 놓인 위치를 [세로 방향 좌표, 가로 방향 좌표] 순으로 배열에 담아 return
엣지 케이스는 없었네요~!
배열만 썼습니다.
원래는 매서드 추출을 해야하지만...!
너무 귀찮았기에 입력값 중 방향에 따른 로직을 반복문 안에 넣었어요.
경계 밖으로 나가는지와 경로에 장애물이 있는지만 확인했습니다.
조금 귀찮고 재미없는 문제였습니다...!
---------------------------------------------------------------------------------------------------------------------------------------------
- 추억의 천지인 같은 키보드가 주어집니다.
- 그리고 입력해야하는 문자열들이 주어집니다.
- 주어진 문자열을 치기 위하여 총 몇번 타건해야하는지 물어보는 문제입니다.
Hash를 활용하여 문제를 풀었습니다.
입력:
- 1번 키부터 차례대로 할당된 문자들이 순서대로 담긴 문자열배열 keymap
- 입력하려는 문자열들이 담긴 문자열 배열 targets
출력:
-  각 문자열을 작성하기 위해 키를 최소 몇 번씩 …
> [7월 3주/ 8월 첫주차 알고리즘 스터디] 프로그래머스 자유문제풀이 / 이주희
